compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
machine_rank: 0
main_training_function: main
num_processes: 4
num_machines: 1
# 仅保留必要的 DeepSpeed 路径指向
deepspeed_config:
  deepspeed_config_file: /caizhenyang/panghuaiwen/legal_LLM/HuatuoGPT-o1/configs/deepspeed_config.json
  deepspeed_multinode_launcher: standard